### ISSUE TITLE
Шедулер ⏳

### ISSUE THREAD

**Issue by dura0ok** [Concert-Mate/Users-Service#22]
> Реализовать шедулер (будь то компонент Users-Service или отдельный сервис). Он будет с некоторой периодичностью узнавать текущие актуальные концерты (через взаимодействие с Music-Service) и отправлять сообщения об отправке уведомлений телеграмм-боту через RabbitMQ.

**Comment by pipichinka** [comment]
![RdHLJWHe858.jpg](https://github.com/Concerts-Mate/Users-Service/assets/89928654/13ef2559-b92a-411a-b139-11a7795b7602)

**Comment by pipichinka** [comment]
Шэдулер есть? есть. значит ГОЙДА
